package com.gestourant.restaurant;
import jakarta.validation.Valid; import jakarta.validation.constraints.Min; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController @RequestMapping("/api/tables")
public class TableController { private final RestaurantTableRepository tables; private final com.gestourant.order.GuestOrderRequestRepository guestRequests; public TableController(RestaurantTableRepository t,com.gestourant.order.GuestOrderRequestRepository g){tables=t;guestRequests=g;}
 @GetMapping public List<RestaurantTable> list(){return tables.findAll();}
 @PostMapping @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") @ResponseStatus(HttpStatus.CREATED) public RestaurantTable create(@Valid @RequestBody TableRequest r){if(tables.existsByTableNumber(r.tableNumber()))throw new IllegalArgumentException("El número de mesa ya existe");RestaurantTable table=new RestaurantTable(r.tableNumber(),r.seats());long index=tables.count();table.updateFloorPosition(14.0+(index%4)*24.0,24.0+((index/4)%4)*21.0);return tables.save(table);}
 @PutMapping("/{id}") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") public RestaurantTable update(@PathVariable Long id,@Valid @RequestBody TableRequest r){RestaurantTable t=tables.findById(id).orElseThrow(()->new IllegalArgumentException("Mesa no encontrada")); if(!t.getTableNumber().equals(r.tableNumber())&&tables.existsByTableNumber(r.tableNumber()))throw new IllegalArgumentException("El número de mesa ya existe");t.update(r.tableNumber(),r.seats());return tables.save(t);}
 @PatchMapping("/{id}/position") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") public RestaurantTable updatePosition(@PathVariable Long id,@Valid @RequestBody FloorPositionRequest r){RestaurantTable t=tables.findById(id).orElseThrow(()->new IllegalArgumentException("Mesa no encontrada"));t.updateFloorPosition(r.x(),r.y());return tables.save(t);}
 @DeleteMapping("/{id}") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable Long id){RestaurantTable table=tables.findById(id).orElseThrow(()->new IllegalArgumentException("Mesa no encontrada"));if(table.getStatus()==TableStatus.OCUPADA)throw new IllegalArgumentException("No puedes eliminar una mesa ocupada");if(guestRequests.existsByTableId(table.getId()))throw new IllegalArgumentException("Esta mesa ya tiene historial de pedidos QR y no se puede eliminar");if(table.getJoinedTableId()!=null){tables.findById(table.getJoinedTableId()).ifPresent(other->{other.unjoin();tables.save(other);});}tables.delete(table);}
 @PostMapping("/join") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") public List<RestaurantTable> join(@Valid @RequestBody JoinRequest request){if(request.firstTableId().equals(request.secondTableId()))throw new IllegalArgumentException("Selecciona dos mesas diferentes");RestaurantTable first=tables.findById(request.firstTableId()).orElseThrow(()->new IllegalArgumentException("Primera mesa no encontrada"));RestaurantTable second=tables.findById(request.secondTableId()).orElseThrow(()->new IllegalArgumentException("Segunda mesa no encontrada"));if(first.getStatus()==TableStatus.OCUPADA||second.getStatus()==TableStatus.OCUPADA)throw new IllegalArgumentException("Solo puedes unir mesas libres");if(guestRequests.existsByTableIdAndStatusIn(first.getId(),List.of(com.gestourant.order.GuestRequestStatus.PENDIENTE,com.gestourant.order.GuestRequestStatus.EN_COCINA,com.gestourant.order.GuestRequestStatus.PREPARANDO))||guestRequests.existsByTableIdAndStatusIn(second.getId(),List.of(com.gestourant.order.GuestRequestStatus.PENDIENTE,com.gestourant.order.GuestRequestStatus.EN_COCINA,com.gestourant.order.GuestRequestStatus.PREPARANDO)))throw new IllegalArgumentException("Atiende las solicitudes QR antes de unir estas mesas");if(first.getJoinedTableId()!=null||second.getJoinedTableId()!=null)throw new IllegalArgumentException("Una de las mesas ya está unida");first.joinWith(second.getId());second.joinWith(first.getId());return tables.saveAll(List.of(first,second));}
 @DeleteMapping("/join") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") @ResponseStatus(HttpStatus.NO_CONTENT) public void unjoin(@Valid @RequestBody JoinRequest request){RestaurantTable first=tables.findById(request.firstTableId()).orElseThrow(()->new IllegalArgumentException("Primera mesa no encontrada"));RestaurantTable second=tables.findById(request.secondTableId()).orElseThrow(()->new IllegalArgumentException("Segunda mesa no encontrada"));first.unjoin();second.unjoin();tables.saveAll(List.of(first,second));}
 public record TableRequest(@Min(1) Integer tableNumber,@Min(1) Integer seats){} public record JoinRequest(Long firstTableId,Long secondTableId){} public record FloorPositionRequest(@jakarta.validation.constraints.DecimalMin("5.0") @jakarta.validation.constraints.DecimalMax("95.0") Double x,@jakarta.validation.constraints.DecimalMin("8.0") @jakarta.validation.constraints.DecimalMax("90.0") Double y){}
}
