package com.gestourant.restaurant;
import jakarta.validation.Valid; import jakarta.validation.constraints.Min; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController @RequestMapping("/api/tables")
public class TableController { private final RestaurantTableRepository tables; public TableController(RestaurantTableRepository t){tables=t;}
 @GetMapping public List<RestaurantTable> list(){return tables.findAll();}
 @PostMapping @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") @ResponseStatus(HttpStatus.CREATED) public RestaurantTable create(@Valid @RequestBody TableRequest r){if(tables.existsByTableNumber(r.tableNumber()))throw new IllegalArgumentException("El número de mesa ya existe");return tables.save(new RestaurantTable(r.tableNumber(),r.seats()));}
 @PutMapping("/{id}") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") public RestaurantTable update(@PathVariable Long id,@Valid @RequestBody TableRequest r){RestaurantTable t=tables.findById(id).orElseThrow(()->new IllegalArgumentException("Mesa no encontrada")); if(!t.getTableNumber().equals(r.tableNumber())&&tables.existsByTableNumber(r.tableNumber()))throw new IllegalArgumentException("El número de mesa ya existe");t.update(r.tableNumber(),r.seats());return tables.save(t);}
 @DeleteMapping("/{id}") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable Long id){RestaurantTable table=tables.findById(id).orElseThrow(()->new IllegalArgumentException("Mesa no encontrada"));if(table.getStatus()==TableStatus.OCUPADA)throw new IllegalArgumentException("No puedes eliminar una mesa ocupada");if(table.getJoinedTableId()!=null){tables.findById(table.getJoinedTableId()).ifPresent(other->{other.unjoin();tables.save(other);});}tables.delete(table);}
 @PostMapping("/join") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") public List<RestaurantTable> join(@Valid @RequestBody JoinRequest request){if(request.firstTableId().equals(request.secondTableId()))throw new IllegalArgumentException("Selecciona dos mesas diferentes");RestaurantTable first=tables.findById(request.firstTableId()).orElseThrow(()->new IllegalArgumentException("Primera mesa no encontrada"));RestaurantTable second=tables.findById(request.secondTableId()).orElseThrow(()->new IllegalArgumentException("Segunda mesa no encontrada"));if(first.getStatus()==TableStatus.OCUPADA||second.getStatus()==TableStatus.OCUPADA)throw new IllegalArgumentException("Solo puedes unir mesas libres");if(first.getJoinedTableId()!=null||second.getJoinedTableId()!=null)throw new IllegalArgumentException("Una de las mesas ya está unida");first.joinWith(second.getId());second.joinWith(first.getId());return tables.saveAll(List.of(first,second));}
 @DeleteMapping("/join") @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMINISTRADOR')") @ResponseStatus(HttpStatus.NO_CONTENT) public void unjoin(@Valid @RequestBody JoinRequest request){RestaurantTable first=tables.findById(request.firstTableId()).orElseThrow(()->new IllegalArgumentException("Primera mesa no encontrada"));RestaurantTable second=tables.findById(request.secondTableId()).orElseThrow(()->new IllegalArgumentException("Segunda mesa no encontrada"));first.unjoin();second.unjoin();tables.saveAll(List.of(first,second));}
 public record TableRequest(@Min(1) Integer tableNumber,@Min(1) Integer seats){} public record JoinRequest(Long firstTableId,Long secondTableId){}
}
