package com.gestourant.order;
import com.gestourant.catalog.*; import com.gestourant.restaurant.*; import com.gestourant.user.*; import jakarta.transaction.Transactional; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import java.time.*; import java.math.BigDecimal; import java.util.*; import org.slf4j.Logger; import org.slf4j.LoggerFactory;
@Service public class OrderService { private static final Logger log=LoggerFactory.getLogger(OrderService.class); private final RestaurantTableRepository tables; private final RestaurantOrderRepository orders; private final ProductRepository products; private final InvoiceRepository invoices; private final UserRepository users; public OrderService(RestaurantTableRepository t,RestaurantOrderRepository o,ProductRepository p,InvoiceRepository i,UserRepository u){tables=t;orders=o;products=p;invoices=i;users=u;}
 @Transactional public RestaurantOrder open(Long tableId){RestaurantTable table=tables.findById(tableId).orElseThrow(()->new IllegalArgumentException("Mesa no encontrada"));if(table.getStatus()==TableStatus.OCUPADA)throw new IllegalArgumentException("La mesa ya está ocupada");User user=currentUser();table.occupy();RestaurantOrder order=orders.save(new RestaurantOrder(table,user));log.info("Order opened orderId={} tableId={} user={}",order.getId(),tableId,user.getUsername());return order;}
 @Transactional public RestaurantOrder addItem(Long orderId,Long productId,int quantity){RestaurantOrder order=getOpen(orderId);Product product=products.findById(productId).orElseThrow(()->new IllegalArgumentException("Producto no encontrado"));if(!product.isActive())throw new IllegalArgumentException("El producto no está disponible");product.reduceStock(quantity);order.addItem(new OrderItem(order,product,quantity));return orders.save(order);}
 @Transactional public Invoice close(Long orderId,PaymentMethod method){RestaurantOrder order=getOpen(orderId);if(order.getItems().isEmpty())throw new IllegalArgumentException("El pedido no tiene productos");order.close();order.getTable().free();Invoice invoice=invoices.save(new Invoice(order,method));log.info("Order closed orderId={} invoice={} total={} payment={}",orderId,invoice.getInvoiceNumber(),invoice.getTotal(),method);return invoice;}
 public RestaurantOrder get(Long id){return orders.findById(id).orElseThrow(()->new IllegalArgumentException("Pedido no encontrado"));} public RestaurantOrder getOpenByTable(Long tableId){return orders.findByTableIdAndStatus(tableId,OrderStatus.ABIERTA).orElseThrow(()->new IllegalArgumentException("No hay un pedido abierto para esta mesa"));} private RestaurantOrder getOpen(Long id){RestaurantOrder o=get(id);if(o.getStatus()!=OrderStatus.ABIERTA)throw new IllegalArgumentException("El pedido ya fue cerrado");return o;} private User currentUser(){String email=SecurityContextHolder.getContext().getAuthentication().getName();return users.findByEmailIgnoreCase(email).orElseThrow(()->new IllegalStateException("Usuario no encontrado"));}
 public CashClose cashClose(LocalDate date){List<Invoice> list=invoices.findByIssuedAtBetween(date.atStartOfDay(),date.plusDays(1).atStartOfDay());BigDecimal cash=sum(list,PaymentMethod.EFECTIVO), digital=sum(list,PaymentMethod.DIGITAL);return new CashClose(date,cash,digital,cash.add(digital),list.size());} private BigDecimal sum(List<Invoice> list,PaymentMethod method){return list.stream().filter(i->i.getPaymentMethod()==method).map(Invoice::getTotal).reduce(BigDecimal.ZERO,BigDecimal::add);} public record CashClose(LocalDate date,BigDecimal efectivo,BigDecimal digital,BigDecimal total,long facturas){}
}
